invisible( '
Generated by claude sonnet 3.7; prompt: 
Construct a network plot using R and igraph. 
Arcs should be drawn using "donor" and "recipient" in the D csv. 
I would like a "tree" layout. 
Nodes should appear as follows: 
* Suppress node labels throughout 
* default shape and colour is open circile 
* nodes with ticu that is not Inf should be filled red triangle 
* those with thospital not Inf should be filled red square

Line type should depend on "contacttype" 
:F should be solid arrow 
:G should be dashed 
:H should be squiggly or if not available dotted 

Finally increase size logarathmically with outdegree 
')
# Load required libraries
library(igraph)
library(readr)

# Read the CSV files
nodes_data <- read_csv("../defaultforest-gen4-G.csv")
edges_data <- read_csv("../defaultforest-gen4-D.csv")

# Create the graph structure
# First, create an empty graph
g <- make_empty_graph(directed = TRUE)

# Add all vertices (nodes) from the nodes_data frame
all_nodes <- unique(nodes_data$pid)
g <- add_vertices(g, length(all_nodes), name = all_nodes)

# Add all edges from the edges_data frame
edge_list <- matrix(ncol = 2, nrow = 0)
edge_types <- character(0)

for (i in 1:nrow(edges_data)) {
  source_node <- which(all_nodes == edges_data$donor[i])
  target_node <- which(all_nodes == edges_data$recipient[i])
  
  if (length(source_node) > 0 && length(target_node) > 0) {
    edge_list <- rbind(edge_list, c(source_node, target_node))
    edge_types <- c(edge_types, edges_data$contacttype[i])
  }
}

# Add all edges at once for better performance
if (nrow(edge_list) > 0) {
  g <- add_edges(g, t(edge_list))
  E(g)$contact_type <- edge_types
}

# Calculate outdegree for each node for node sizing
outdegree <- degree(g, mode = "out")
outdegree[is.na(outdegree)] <- 0  # Set NA values to 0
# Apply logarithm for sizing, adding 1 to avoid log(0)
v_size <- log(outdegree + 1) * 3 + 3  # Scale for visibility

# Set node attributes based on hospital and ICU status
V(g)$shape <- "circle"  # Default shape
V(g)$color <- "black"   # Default color for outline
V(g)$fill <- "white"    # Default fill color (open circle)

# Create a function to check if a value is finite (not "Inf")
is_finite_val <- function(x) {
  return(!is.na(x) && x != "Inf" && !is.infinite(as.numeric(x)))
}

# Set attributes for nodes based on hospital and ICU status
for (i in 1:length(all_nodes)) {
  node_id <- all_nodes[i]
  node_row <- nodes_data[nodes_data$pid == node_id, ]
  
  if (nrow(node_row) > 0) {
    # Check ICU status first (red triangle)
    if (is_finite_val(node_row$ticu)) {
      V(g)[i]$shape <- "circle"  # Changed from triangle to circle with filled red
      V(g)[i]$fill <- "red"
    }
    # Then check hospital status (red square) - only if not already set by ICU
    else if (is_finite_val(node_row$thospital)) {
      V(g)[i]$shape <- "square"
      V(g)[i]$fill <- "red"
    }
  }
}

# Set edge attributes based on contact type
E(g)$lty <- 1  # Default solid line
edge_types <- E(g)$contact_type

for (i in 1:length(E(g))) {
  if (edge_types[i] == "F") {
    E(g)[i]$lty <- 1  # Solid line for F
  } else if (edge_types[i] == "G") {
    E(g)[i]$lty <- 2  # Dashed line for G
  } else if (edge_types[i] == "H") {
    E(g)[i]$lty <- 3  # Dotted line for H (as squiggly is not available)
  }
}

# Try to use the tree layout, but have a fallback
tryCatch({
  tree_layout <- layout_as_tree(g)
}, error = function(e) {
  # If tree layout fails, use a different layout algorithm
  tree_layout <- layout_with_fr(g)
  cat("Tree layout failed, using Fruchterman-Reingold layout instead\n")
})

# Create a PDF file
pdf("network_plot.pdf", width = 12, height = 10)

# Plot the graph
par(mar = c(1, 1, 1, 1))
plot(g,
     layout = tree_layout,
     vertex.size = v_size,        
     vertex.shape = V(g)$shape,   
     vertex.color = V(g)$fill,    
     vertex.frame.color = V(g)$color,
     edge.lty = E(g)$lty,         
     edge.arrow.size = 0.5,       
     vertex.label = NA            # Suppress node labels
)

# Add a legend
legend("bottomleft", 
       legend = c("Default (open circle)", "Hospital (red square)", "ICU (red circle)", "F contact", "G contact", "H contact"),
       pch = c(1, 0, 1, NA, NA, NA),
       lty = c(NA, NA, NA, 1, 2, 3),
       col = c("black", "red", "red", "black", "black", "black"),
       pt.bg = c("white", "red", "red", NA, NA, NA),
       bty = "n")

# Close the PDF device
dev.off()

# Also create a PNG version
png("network_plot.png", width = 1200, height = 1000)
par(mar = c(1, 1, 1, 1))

plot(g,
     layout = tree_layout,
     vertex.size = v_size,
     vertex.shape = V(g)$shape,
     vertex.color = V(g)$fill,
     vertex.frame.color = V(g)$color,
     edge.lty = E(g)$lty,
     edge.arrow.size = 0.5,
     vertex.label = NA
)

legend("bottomleft", 
       legend = c("Default", "Hospital", "ICU", "F contact", "G contact", "H contact"),
       pch = c(1, 0, 2, NA, NA, NA),
       lty = c(NA, NA, NA, 1, 2, 3),
       col = c("black", "red", "red", "black", "black", "black"),
       pt.bg = c("white", "red", "red", NA, NA, NA),
       bty = "n")

dev.off()

# Print a message when done
cat("Network plot created as 'network_plot.pdf' and 'network_plot.png'\n")
